In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


In [7]:
%cd C:\Users\Faiz\Desktop\Acmegrade internship stuff

C:\Users\Faiz\Desktop\Acmegrade internship stuff


In [8]:
df1 = pd.read_excel("Data Preprocessing Data File.xlsx")
print(df1)

   Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes


In [9]:
x = df1.iloc [:,:-1]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [11]:
y = df1.iloc[:,3].values
print (y)


['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [17]:
x1=df1.iloc[:,1:2]
x1

Age 
0  44.0
1  27.0
2   NaN
3  39.0
4   NaN
5  35.0
6  39.0
7  48.0
8  50.0
9  37.0

In [19]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
si.fit_transform(x1)


array([[44.   ],
       [27.   ],
       [39.875],
       [39.   ],
       [39.875],
       [35.   ],
       [39.   ],
       [48.   ],
       [50.   ],
       [37.   ]])

In [20]:
from sklearn.impute import SimpleImputer
si = SimpleImputer( strategy= 'median',)
si.fit_transform(x1)

array([[44.],
       [27.],
       [39.],
       [39.],
       [39.],
       [35.],
       [39.],
       [48.],
       [50.],
       [37.]])

In [21]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='most_frequent')
si.fit_transform(x1)

array([[44.],
       [27.],
       [39.],
       [39.],
       [39.],
       [35.],
       [39.],
       [48.],
       [50.],
       [37.]])