In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


In [3]:
%cd C:\Users\Faiz\Desktop\Data

C:\Users\Faiz\Desktop\Data


In [4]:
df1 = pd.read_excel("Data Preprocessing Data File.xlsx")
print(df1)

   Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes


In [5]:
x = df1.iloc[:,:-1]
x

Country   Age   Salary 
0   France   44.0  72000.0
1       NaN  27.0  48000.0
2  Germany    NaN  54000.0
3    Spain   39.0      NaN
4  Germany    NaN  64000.0
5   France   35.0  58000.0
6    Spain   39.0  52000.0
7   France   48.0      NaN
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [6]:
x = df1.iloc[:,:-1].values
x

array([['France ', 44.0, 72000.0],
       [nan, 27.0, 48000.0],
       ['Germany ', nan, 54000.0],
       ['Spain ', 39.0, nan],
       ['Germany ', nan, 64000.0],
       ['France ', 35.0, 58000.0],
       ['Spain ', 39.0, 52000.0],
       ['France ', 48.0, nan],
       ['Germany ', 50.0, 83000.0],
       ['France ', 37.0, 67000.0]], dtype=object)

In [7]:
y = df1.iloc[:,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [8]:
x[:,1:2]

array([[44.0],
       [27.0],
       [nan],
       [39.0],
       [nan],
       [35.0],
       [39.0],
       [48.0],
       [50.0],
       [37.0]], dtype=object)

In [9]:
from sklearn.impute import SimpleImputer
si = SimpleImputer()
x [:,1:2]= si.fit_transform(x[:,1:2])
print (x)


[['France ' 44.0 72000.0]
 [nan 27.0 48000.0]
 ['Germany ' 39.875 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 39.875 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [10]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='most_frequent')
x [:,0:1]= si.fit_transform(x[:,0:1])
print (x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 39.875 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 39.875 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform (x[:,0])

array([0, 0, 1, 2, 1, 0, 2, 0, 1, 0])

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,0] = le.fit_transform (x[:,0])
print(x)

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 39.875 54000.0]
 [2 39.0 nan]
 [1 39.875 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 nan]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print (x)


[[1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 39.875 54000.0]
 [0.0 0.0 1.0 39.0 nan]
 [0.0 1.0 0.0 39.875 64000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.0 52000.0]
 [1.0 0.0 0.0 48.0 nan]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
#watched till one hour 