In [3]:
import numpy as np

In [5]:
np.array([[10,20,30,40],[50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [6]:
np.array([[10,20,30,False],[50,60,70,True]])

array([[10, 20, 30,  0],
       [50, 60, 70,  1]])

In [7]:
np.array([[10,20,30,40],[50,60,np.nan,80]])

array([[10., 20., 30., 40.],
       [50., 60., nan, 80.]])

In [8]:
l1 = [10,20,30,40,50,60]
l1

[10, 20, 30, 40, 50, 60]

In [11]:
l2 = l1[2:5]
print(l1)
print(l2)

[10, 20, 30, 40, 50, 60]
[30, 40, 50]


In [12]:
ar1 = np.array(l1)
ar1

array([10, 20, 30, 40, 50, 60])

In [13]:
ar2 = ar1[2:5]
print(ar2)

[30 40 50]


In [16]:
ar2[1]=444
print(ar2)
print(ar1)

[ 30 444  50]
[ 10  20  30 444  50  60]


In [18]:
ar1 = np.array(l1)
ar2 = ar1[2:5].copy()
ar2[2]=444
print(ar2)
print(ar1)

[ 30  40 444]
[10 20 30 40 50 60]


In [21]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a = np.arange(20,10,-2)
a

array([20, 18, 16, 14, 12])

In [5]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
a.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [10]:
a = np.zeros((5,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
a = np.ones((5,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
a = np.ones((5,5))
a*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [17]:
mat1 = np.arange(30)
mat2 = np.reshape(mat1,(5,6),"C")
print(mat1)
print(mat2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [18]:
mat2.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [20]:
mat2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
vector = np.linspace(20,40,8)
vector

array([20.        , 22.85714286, 25.71428571, 28.57142857, 31.42857143,
       34.28571429, 37.14285714, 40.        ])

In [22]:
arr1 = np.arange(200,300)
arr1

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212,
       213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
       226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238,
       239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
       252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264,
       265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277,
       278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290,
       291, 292, 293, 294, 295, 296, 297, 298, 299])

In [23]:
print(arr1[:20],'\n')

[200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219] 



In [24]:
print(arr1[::10],'\n')

[200 210 220 230 240 250 260 270 280 290] 



In [25]:
arr_slice = slice(1,10,2)
print(arr_slice)
print(arr1[arr_slice])

slice(1, 10, 2)
[201 203 205 207 209]


In [30]:
arr1 = np.arange(30)
arr2 = arr1.reshape(5,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [32]:
arr2[2:4,2:5]

array([[14, 15, 16],
       [20, 21, 22]])

In [33]:
print(arr1.shape)

(30,)


In [38]:
print(arr1.min())
print(arr1.max())

0
29


In [40]:
arr1 = np.array([1,2,3,0], dtype=bool)
arr1

array([ True,  True,  True, False])

In [42]:
arr = np.array(['apple','cherry','banana'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [43]:
arr = np.array(['apple','cherry','banana'])
print(np.sort(arr)[::-1])

['cherry' 'banana' 'apple']
